import { Pattern, Question } from "./data";

// Helper function to create question objects
const q = (id: string, title: string, difficulty: "Easy" | "Medium" | "Hard", link: string, pattern: string): Question => ({
    id, title, difficulty, link, pattern, completed: false
});

// Additional questions for EXISTING patterns (to be merged)
export const additionalQuestionsForExistingPatterns: { [slug: string]: Question[] } = {
    // Two Pointers (id: 2) - additional questions
    "two-pointers": [
        q("2-5", "Partition Labels", "Medium", "https://leetcode.com/problems/partition-labels/", "two-pointers"),
        q("2-6", "Sort Colors", "Medium", "https://leetcode.com/problems/sort-colors/", "two-pointers"),
        q("2-7", "Maximum Number of Visible Points", "Hard", "https://leetcode.com/problems/maximum-number-of-visible-points/", "two-pointers"),
        q("2-8", "Subarrays with K Different Integers", "Hard", "https://leetcode.com/problems/subarrays-with-k-different-integers/", "two-pointers"),
    ],
    // Sliding Window (id: 3) - additional questions
    "sliding-window": [
        q("3-5", "Longest Substring with At Least K Repeating Characters", "Medium", "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/", "sliding-window"),
        q("3-6", "Max Consecutive Ones III", "Medium", "https://leetcode.com/problems/max-consecutive-ones-iii/", "sliding-window"),
        q("3-7", "Grumpy Bookstore Owner", "Medium", "https://leetcode.com/problems/grumpy-bookstore-owner/", "sliding-window"),
        q("3-8", "Sliding Window Median", "Hard", "https://leetcode.com/problems/sliding-window-median/", "sliding-window"),
    ],
    // DFS (id: 11) - additional questions
    "dfs": [
        q("11-4", "Letter Combinations of a Phone Number", "Medium", "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", "dfs"),
        q("11-5", "Decode String", "Medium", "https://leetcode.com/problems/decode-string/", "dfs"),
        q("11-6", "Number of Provinces", "Medium", "https://leetcode.com/problems/number-of-provinces/", "dfs"),
        q("11-7", "Shortest Bridge", "Medium", "https://leetcode.com/problems/shortest-bridge/", "dfs"),
        q("11-8", "All Paths From Source to Target", "Medium", "https://leetcode.com/problems/all-paths-from-source-to-target/", "dfs"),
        q("11-9", "Surrounded Regions", "Medium", "https://leetcode.com/problems/surrounded-regions/", "dfs"),
        q("11-10", "House Robber III", "Medium", "https://leetcode.com/problems/house-robber-iii/", "dfs"),
        q("11-11", "Critical Connections in a Network", "Hard", "https://leetcode.com/problems/critical-connections-in-a-network/", "dfs"),
        q("11-12", "Remove Invalid Parentheses", "Hard", "https://leetcode.com/problems/remove-invalid-parentheses/", "dfs"),
        q("11-13", "Longest Increasing Path in a Matrix", "Hard", "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", "dfs"),
        q("11-14", "Concatenated Words", "Hard", "https://leetcode.com/problems/concatenated-words/", "dfs"),
        q("11-15", "Making A Large Island", "Hard", "https://leetcode.com/problems/making-a-large-island/", "dfs"),
        q("11-16", "Contain Virus", "Hard", "https://leetcode.com/problems/contain-virus/", "dfs"),
        q("11-17", "24 Game", "Hard", "https://leetcode.com/problems/24-game/", "dfs"),
        q("11-18", "Remove Boxes", "Hard", "https://leetcode.com/problems/remove-boxes/", "dfs"),
    ],
    // BFS (id: 12) - additional questions
    "bfs": [
        q("12-4", "Number of Islands", "Medium", "https://leetcode.com/problems/number-of-islands/", "bfs"),
        q("12-5", "Snakes and Ladders", "Medium", "https://leetcode.com/problems/snakes-and-ladders/", "bfs"),
        q("12-6", "Is Graph Bipartite?", "Medium", "https://leetcode.com/problems/is-graph-bipartite/", "bfs"),
        q("12-7", "Minimum Jumps to Reach Home", "Medium", "https://leetcode.com/problems/minimum-jumps-to-reach-home/", "bfs"),
        q("12-8", "Word Ladder II", "Hard", "https://leetcode.com/problems/word-ladder-ii/", "bfs"),
        q("12-9", "Cut Off Trees for Golf Event", "Hard", "https://leetcode.com/problems/cut-off-trees-for-golf-event/", "bfs"),
        q("12-10", "Reachable Nodes In Subdivided Graph", "Hard", "https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/", "bfs"),
    ],
    // Backtracking (id: 14) - additional questions
    "backtracking": [
        q("14-4", "Palindrome Partitioning", "Medium", "https://leetcode.com/problems/palindrome-partitioning/", "backtracking"),
        q("14-5", "Combination Sum II", "Medium", "https://leetcode.com/problems/combination-sum-ii/", "backtracking"),
        q("14-6", "Combinations", "Medium", "https://leetcode.com/problems/combinations/", "backtracking"),
        q("14-7", "Permutations II", "Medium", "https://leetcode.com/problems/permutations-ii/", "backtracking"),
        q("14-8", "Subsets II", "Medium", "https://leetcode.com/problems/subsets-ii/", "backtracking"),
        q("14-9", "Beautiful Arrangement", "Medium", "https://leetcode.com/problems/beautiful-arrangement/", "backtracking"),
        q("14-10", "Word Search II", "Hard", "https://leetcode.com/problems/word-search-ii/", "backtracking"),
        q("14-11", "N-Queens", "Hard", "https://leetcode.com/problems/n-queens/", "backtracking"),
        q("14-12", "Unique Paths III", "Hard", "https://leetcode.com/problems/unique-paths-iii/", "backtracking"),
    ],
    // Dynamic Programming (id: 15) - additional questions
    "dynamic-programming": [
        q("15-8", "Maximum Subarray", "Easy", "https://leetcode.com/problems/maximum-subarray/", "dynamic-programming"),
        q("15-9", "Divisor Game", "Easy", "https://leetcode.com/problems/divisor-game/", "dynamic-programming"),
        q("15-10", "Counting Bits", "Easy", "https://leetcode.com/problems/counting-bits/", "dynamic-programming"),
        q("15-11", "Decode Ways", "Medium", "https://leetcode.com/problems/decode-ways/", "dynamic-programming"),
        q("15-12", "Word Break", "Medium", "https://leetcode.com/problems/word-break/", "dynamic-programming"),
        q("15-13", "Delete and Earn", "Medium", "https://leetcode.com/problems/delete-and-earn/", "dynamic-programming"),
        q("15-14", "Maximal Square", "Medium", "https://leetcode.com/problems/maximal-square/", "dynamic-programming"),
        q("15-15", "Maximum Product Subarray", "Medium", "https://leetcode.com/problems/maximum-product-subarray/", "dynamic-programming"),
        q("15-16", "Maximum Length of Repeated Subarray", "Medium", "https://leetcode.com/problems/maximum-length-of-repeated-subarray/", "dynamic-programming"),
        q("15-17", "Palindromic Substrings", "Medium", "https://leetcode.com/problems/palindromic-substrings/", "dynamic-programming"),
        q("15-18", "Continuous Subarray Sum", "Medium", "https://leetcode.com/problems/continuous-subarray-sum/", "dynamic-programming"),
        q("15-19", "Knight Dialer", "Medium", "https://leetcode.com/problems/knight-dialer/", "dynamic-programming"),
        q("15-20", "Count Square Submatrices with All Ones", "Medium", "https://leetcode.com/problems/count-square-submatrices-with-all-ones/", "dynamic-programming"),
        q("15-21", "Range Sum Query 2D - Immutable", "Medium", "https://leetcode.com/problems/range-sum-query-2d-immutable/", "dynamic-programming"),
        q("15-22", "Longest Arithmetic Subsequence", "Medium", "https://leetcode.com/problems/longest-arithmetic-subsequence/", "dynamic-programming"),
        q("15-23", "Trapping Rain Water", "Hard", "https://leetcode.com/problems/trapping-rain-water/", "dynamic-programming"),
        q("15-24", "Word Break II", "Hard", "https://leetcode.com/problems/word-break-ii/", "dynamic-programming"),
        q("15-25", "Regular Expression Matching", "Hard", "https://leetcode.com/problems/regular-expression-matching/", "dynamic-programming"),
        q("15-26", "Maximal Rectangle", "Hard", "https://leetcode.com/problems/maximal-rectangle/", "dynamic-programming"),
        q("15-27", "Longest Valid Parentheses", "Hard", "https://leetcode.com/problems/longest-valid-parentheses/", "dynamic-programming"),
        q("15-28", "Minimum Difficulty of a Job Schedule", "Hard", "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/", "dynamic-programming"),
        q("15-29", "Frog Jump", "Hard", "https://leetcode.com/problems/frog-jump/", "dynamic-programming"),
        q("15-30", "Best Time to Buy and Sell Stock IV", "Hard", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", "dynamic-programming"),
        q("15-31", "Burst Balloons", "Hard", "https://leetcode.com/problems/burst-balloons/", "dynamic-programming"),
        q("15-32", "Minimum Cost to Merge Stones", "Hard", "https://leetcode.com/problems/minimum-cost-to-merge-stones/", "dynamic-programming"),
        q("15-33", "Minimum Insertion Steps to Make a String Palindrome", "Hard", "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", "dynamic-programming"),
        q("15-34", "Super Egg Drop", "Hard", "https://leetcode.com/problems/super-egg-drop/", "dynamic-programming"),
        q("15-35", "Count Different Palindromic Subsequences", "Hard", "https://leetcode.com/problems/count-different-palindromic-subsequences/", "dynamic-programming"),
        q("15-36", "Minimum Cost to Cut a Stick", "Hard", "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", "dynamic-programming"),
    ],
};

// NEW patterns that don't exist in the original data
export const newPatterns: Pattern[] = [
    {
        id: "16",
        title: "Arrays",
        description: "Fundamental array operations including traversal, manipulation, and optimization techniques.",
        slug: "arrays",
        questions: [
            // EASY
            q("16-1", "Two Sum", "Easy", "https://leetcode.com/problems/two-sum/", "arrays"),
            q("16-2", "Best Time to Buy and Sell Stock", "Easy", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "arrays"),
            q("16-3", "Plus One", "Easy", "https://leetcode.com/problems/plus-one/", "arrays"),
            q("16-4", "Move Zeroes", "Easy", "https://leetcode.com/problems/move-zeroes/", "arrays"),
            q("16-5", "Best Time to Buy and Sell Stock II", "Easy", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", "arrays"),
            q("16-6", "Running Sum of 1d Array", "Easy", "https://leetcode.com/problems/running-sum-of-1d-array/", "arrays"),
            q("16-7", "Find Pivot Index", "Easy", "https://leetcode.com/problems/find-pivot-index/", "arrays"),
            q("16-8", "Majority Element", "Easy", "https://leetcode.com/problems/majority-element/", "arrays"),
            q("16-9", "Fibonacci Number", "Easy", "https://leetcode.com/problems/fibonacci-number/", "arrays"),
            q("16-10", "Squares of a Sorted Array", "Easy", "https://leetcode.com/problems/squares-of-a-sorted-array/", "arrays"),
            q("16-11", "Pascal's Triangle", "Easy", "https://leetcode.com/problems/pascals-triangle/", "arrays"),
            q("16-12", "Remove Duplicates from Sorted Array", "Easy", "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "arrays"),
            // MEDIUM
            q("16-13", "Merge Intervals", "Medium", "https://leetcode.com/problems/merge-intervals/", "arrays"),
            q("16-14", "3Sum", "Medium", "https://leetcode.com/problems/3sum/", "arrays"),
            q("16-15", "Product of Array Except Self", "Medium", "https://leetcode.com/problems/product-of-array-except-self/", "arrays"),
            q("16-16", "Insert Delete GetRandom O(1)", "Medium", "https://leetcode.com/problems/insert-delete-getrandom-o1/", "arrays"),
            q("16-17", "Subarray Sum Equals K", "Medium", "https://leetcode.com/problems/subarray-sum-equals-k/", "arrays"),
            q("16-18", "Next Permutation", "Medium", "https://leetcode.com/problems/next-permutation/", "arrays"),
            q("16-19", "Spiral Matrix", "Medium", "https://leetcode.com/problems/spiral-matrix/", "arrays"),
            q("16-20", "Container With Most Water", "Medium", "https://leetcode.com/problems/container-with-most-water/", "arrays"),
            q("16-21", "Rotate Image", "Medium", "https://leetcode.com/problems/rotate-image/", "arrays"),
            q("16-22", "Word Search", "Medium", "https://leetcode.com/problems/word-search/", "arrays"),
            q("16-23", "3Sum Closest", "Medium", "https://leetcode.com/problems/3sum-closest/", "arrays"),
            q("16-24", "Game of Life", "Medium", "https://leetcode.com/problems/game-of-life/", "arrays"),
            q("16-25", "Pairs of Songs With Total Durations Divisible by 60", "Medium", "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/", "arrays"),
            q("16-26", "4Sum", "Medium", "https://leetcode.com/problems/4sum/", "arrays"),
            q("16-27", "Find the Duplicate Number", "Medium", "https://leetcode.com/problems/find-the-duplicate-number/", "arrays"),
            q("16-28", "Combination Sum", "Medium", "https://leetcode.com/problems/combination-sum/", "arrays"),
            q("16-29", "Jump Game II", "Medium", "https://leetcode.com/problems/jump-game-ii/", "arrays"),
            q("16-30", "Maximum Points You Can Obtain from Cards", "Medium", "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/", "arrays"),
            q("16-31", "Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts", "Medium", "https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts/", "arrays"),
            q("16-32", "Max Area of Island", "Medium", "https://leetcode.com/problems/max-area-of-island/", "arrays"),
            q("16-33", "Find All Duplicates in an Array", "Medium", "https://leetcode.com/problems/find-all-duplicates-in-an-array/", "arrays"),
            q("16-34", "K-diff Pairs in an Array", "Medium", "https://leetcode.com/problems/k-diff-pairs-in-an-array/", "arrays"),
            q("16-35", "Subsets", "Medium", "https://leetcode.com/problems/subsets/", "arrays"),
            q("16-36", "Invalid Transactions", "Medium", "https://leetcode.com/problems/invalid-transactions/", "arrays"),
            q("16-37", "Jump Game", "Medium", "https://leetcode.com/problems/jump-game/", "arrays"),
            q("16-38", "Subarray Sums Divisible by K", "Medium", "https://leetcode.com/problems/subarray-sums-divisible-by-k/", "arrays"),
            // HARD
            q("16-39", "First Missing Positive", "Hard", "https://leetcode.com/problems/first-missing-positive/", "arrays"),
            q("16-40", "Largest Rectangle in Histogram", "Hard", "https://leetcode.com/problems/largest-rectangle-in-histogram/", "arrays"),
            q("16-41", "Insert Delete GetRandom O(1) - Duplicates allowed", "Hard", "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/", "arrays"),
            q("16-42", "Best Time to Buy and Sell Stock III", "Hard", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", "arrays"),
            q("16-43", "Max Value of Equation", "Hard", "https://leetcode.com/problems/max-value-of-equation/", "arrays"),
        ]
    },
    {
        id: "17",
        title: "Strings",
        description: "String manipulation, parsing, and pattern matching techniques.",
        slug: "strings",
        questions: [
            // EASY
            q("17-1", "Add Strings", "Easy", "https://leetcode.com/problems/add-strings/", "strings"),
            q("17-2", "Longest Common Prefix", "Easy", "https://leetcode.com/problems/longest-common-prefix/", "strings"),
            q("17-3", "Valid Palindrome II", "Easy", "https://leetcode.com/problems/valid-palindrome-ii/", "strings"),
            q("17-4", "Roman to Integer", "Easy", "https://leetcode.com/problems/roman-to-integer/", "strings"),
            q("17-5", "Implement strStr()", "Easy", "https://leetcode.com/problems/implement-strstr/", "strings"),
            // MEDIUM
            q("17-6", "Longest Substring Without Repeating Characters", "Medium", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "strings"),
            q("17-7", "Minimum Remove to Make Valid Parentheses", "Medium", "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/", "strings"),
            q("17-8", "Longest Palindromic Substring", "Medium", "https://leetcode.com/problems/longest-palindromic-substring/", "strings"),
            q("17-9", "Group Anagrams", "Medium", "https://leetcode.com/problems/group-anagrams/", "strings"),
            q("17-10", "Generate Parentheses", "Medium", "https://leetcode.com/problems/generate-parentheses/", "strings"),
            q("17-11", "Basic Calculator II", "Medium", "https://leetcode.com/problems/basic-calculator-ii/", "strings"),
            q("17-12", "Integer to Roman", "Medium", "https://leetcode.com/problems/integer-to-roman/", "strings"),
            q("17-13", "Reverse Words in a String", "Medium", "https://leetcode.com/problems/reverse-words-in-a-string/", "strings"),
            q("17-14", "Simplify Path", "Medium", "https://leetcode.com/problems/simplify-path/", "strings"),
            q("17-15", "Zigzag Conversion", "Medium", "https://leetcode.com/problems/zigzag-conversion/", "strings"),
            // HARD
            q("17-16", "Text Justification", "Hard", "https://leetcode.com/problems/text-justification/", "strings"),
            q("17-17", "Integer to English Words", "Hard", "https://leetcode.com/problems/integer-to-english-words/", "strings"),
            q("17-18", "Minimum Window Substring", "Hard", "https://leetcode.com/problems/minimum-window-substring/", "strings"),
            q("17-19", "Valid Number", "Hard", "https://leetcode.com/problems/valid-number/", "strings"),
            q("17-20", "Distinct Subsequences", "Hard", "https://leetcode.com/problems/distinct-subsequences/", "strings"),
            q("17-21", "Smallest Range Covering Elements from K Lists", "Hard", "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/", "strings"),
            q("17-22", "Substring with Concatenation of All Words", "Hard", "https://leetcode.com/problems/substring-with-concatenation-of-all-words/", "strings"),
        ]
    },
    {
        id: "18",
        title: "Maths",
        description: "Mathematical concepts including number theory, bit manipulation, and arithmetic operations.",
        slug: "maths",
        questions: [
            // EASY
            q("18-1", "Reverse Integer", "Easy", "https://leetcode.com/problems/reverse-integer/", "maths"),
            q("18-2", "Add Binary", "Easy", "https://leetcode.com/problems/add-binary/", "maths"),
            q("18-3", "Palindrome Number", "Easy", "https://leetcode.com/problems/palindrome-number/", "maths"),
            q("18-4", "Minimum Moves to Equal Array Elements", "Easy", "https://leetcode.com/problems/minimum-moves-to-equal-array-elements/", "maths"),
            q("18-5", "Happy Number", "Easy", "https://leetcode.com/problems/happy-number/", "maths"),
            q("18-6", "Excel Sheet Column Title", "Easy", "https://leetcode.com/problems/excel-sheet-column-title/", "maths"),
            q("18-7", "Missing Number", "Easy", "https://leetcode.com/problems/missing-number/", "maths"),
            q("18-8", "Maximum Product of Three Numbers", "Easy", "https://leetcode.com/problems/maximum-product-of-three-numbers/", "maths"),
            q("18-9", "Power of Two", "Easy", "https://leetcode.com/problems/power-of-two/", "maths"),
            // MEDIUM
            q("18-10", "Encode and Decode TinyURL", "Medium", "https://leetcode.com/problems/encode-and-decode-tinyurl/", "maths"),
            q("18-11", "String to Integer (atoi)", "Medium", "https://leetcode.com/problems/string-to-integer-atoi/", "maths"),
            q("18-12", "Multiply Strings", "Medium", "https://leetcode.com/problems/multiply-strings/", "maths"),
            q("18-13", "Angle Between Hands of a Clock", "Medium", "https://leetcode.com/problems/angle-between-hands-of-a-clock/", "maths"),
            q("18-14", "Integer Break", "Medium", "https://leetcode.com/problems/integer-break/", "maths"),
            q("18-15", "Valid Square", "Medium", "https://leetcode.com/problems/valid-square/", "maths"),
            q("18-16", "The kth Factor of n", "Medium", "https://leetcode.com/problems/the-kth-factor-of-n/", "maths"),
            // HARD
            q("18-17", "Basic Calculator", "Hard", "https://leetcode.com/problems/basic-calculator/", "maths"),
            q("18-18", "Max Points on a Line", "Hard", "https://leetcode.com/problems/max-points-on-a-line/", "maths"),
            q("18-19", "Permutation Sequence", "Hard", "https://leetcode.com/problems/permutation-sequence/", "maths"),
            q("18-20", "Number of Digit One", "Hard", "https://leetcode.com/problems/number-of-digit-one/", "maths"),
        ]
    },
    {
        id: "19",
        title: "Greedy",
        description: "Make locally optimal choices at each step with the hope of finding a global optimum.",
        slug: "greedy",
        questions: [
            // MEDIUM
            q("19-1", "Task Scheduler", "Medium", "https://leetcode.com/problems/task-scheduler/", "greedy"),
            q("19-2", "Gas Station", "Medium", "https://leetcode.com/problems/gas-station/", "greedy"),
            q("19-3", "Minimum Deletion Cost to Avoid Repeating Letters", "Medium", "https://leetcode.com/problems/minimum-deletion-cost-to-avoid-repeating-letters/", "greedy"),
            q("19-4", "Maximum Number of Events That Can Be Attended", "Medium", "https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/", "greedy"),
            q("19-5", "Minimum Deletions to Make Character Frequencies Unique", "Medium", "https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/", "greedy"),
            q("19-6", "Remove K Digits", "Medium", "https://leetcode.com/problems/remove-k-digits/", "greedy"),
            q("19-7", "Restore the Array From Adjacent Pairs", "Medium", "https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/", "greedy"),
            q("19-8", "Non-overlapping Intervals", "Medium", "https://leetcode.com/problems/non-overlapping-intervals/", "greedy"),
            // HARD
            q("19-9", "Candy", "Hard", "https://leetcode.com/problems/candy/", "greedy"),
            q("19-10", "Minimum Number of Taps to Open to Water a Garden", "Hard", "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/", "greedy"),
            q("19-11", "Create Maximum Number", "Hard", "https://leetcode.com/problems/create-maximum-number/", "greedy"),
        ]
    },
    {
        id: "20",
        title: "Tree",
        description: "Binary tree and BST operations including traversals, construction, and path problems.",
        slug: "tree",
        questions: [
            // EASY
            q("20-1", "Diameter of Binary Tree", "Easy", "https://leetcode.com/problems/diameter-of-binary-tree/", "tree"),
            q("20-2", "Invert Binary Tree", "Easy", "https://leetcode.com/problems/invert-binary-tree/", "tree"),
            q("20-3", "Subtree of Another Tree", "Easy", "https://leetcode.com/problems/subtree-of-another-tree/", "tree"),
            q("20-4", "Range Sum of BST", "Easy", "https://leetcode.com/problems/range-sum-of-bst/", "tree"),
            q("20-5", "Symmetric Tree", "Easy", "https://leetcode.com/problems/symmetric-tree/", "tree"),
            q("20-6", "Convert Sorted Array to Binary Search Tree", "Easy", "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", "tree"),
            q("20-7", "Merge Two Binary Trees", "Easy", "https://leetcode.com/problems/merge-two-binary-trees/", "tree"),
            q("20-8", "Maximum Depth of Binary Tree", "Easy", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "tree"),
            q("20-9", "Binary Tree Paths", "Easy", "https://leetcode.com/problems/binary-tree-paths/", "tree"),
            q("20-10", "Same Tree", "Easy", "https://leetcode.com/problems/same-tree/", "tree"),
            q("20-11", "Lowest Common Ancestor of a Binary Search Tree", "Easy", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "tree"),
            q("20-12", "Path Sum", "Easy", "https://leetcode.com/problems/path-sum/", "tree"),
            q("20-13", "Minimum Absolute Difference in BST", "Easy", "https://leetcode.com/problems/minimum-absolute-difference-in-bst/", "tree"),
            q("20-14", "Sum of Left Leaves", "Easy", "https://leetcode.com/problems/sum-of-left-leaves/", "tree"),
            q("20-15", "Balanced Binary Tree", "Easy", "https://leetcode.com/problems/balanced-binary-tree/", "tree"),
            q("20-16", "Binary Tree Inorder Traversal (Using Stack)", "Easy", "https://leetcode.com/problems/binary-tree-inorder-traversal/", "tree"),
            // MEDIUM
            q("20-17", "Count Good Nodes in Binary Tree", "Medium", "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", "tree"),
            q("20-18", "Lowest Common Ancestor of a Binary Tree", "Medium", "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "tree"),
            q("20-19", "Binary Tree Right Side View", "Medium", "https://leetcode.com/problems/binary-tree-right-side-view/", "tree"),
            q("20-20", "All Nodes Distance K in Binary Tree", "Medium", "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", "tree"),
            q("20-21", "Validate Binary Search Tree", "Medium", "https://leetcode.com/problems/validate-binary-search-tree/", "tree"),
            q("20-22", "Binary Tree Zigzag Level Order Traversal", "Medium", "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "tree"),
            q("20-23", "Binary Search Tree Iterator", "Medium", "https://leetcode.com/problems/binary-search-tree-iterator/", "tree"),
            q("20-24", "Binary Tree Level Order Traversal", "Medium", "https://leetcode.com/problems/binary-tree-level-order-traversal/", "tree"),
            q("20-25", "Path Sum III", "Medium", "https://leetcode.com/problems/path-sum-iii/", "tree"),
            q("20-26", "Construct Binary Tree from Preorder and Postorder Traversal", "Medium", "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/", "tree"),
            q("20-27", "Unique Binary Search Trees", "Medium", "https://leetcode.com/problems/unique-binary-search-trees/", "tree"),
            q("20-28", "Recover Binary Search Tree", "Medium", "https://leetcode.com/problems/recover-binary-search-tree/", "tree"),
            q("20-29", "Populating Next Right Pointers in Each Node", "Medium", "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", "tree"),
            q("20-30", "Flatten Binary Tree to Linked List", "Medium", "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "tree"),
            q("20-31", "Maximum Width of Binary Tree", "Medium", "https://leetcode.com/problems/maximum-width-of-binary-tree/", "tree"),
            q("20-32", "Unique Binary Search Trees II", "Medium", "https://leetcode.com/problems/unique-binary-search-trees-ii/", "tree"),
            q("20-33", "Kth Smallest Element in a BST", "Medium", "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "tree"),
            q("20-34", "Redundant Connection", "Medium", "https://leetcode.com/problems/redundant-connection/", "tree"),
            // HARD
            q("20-35", "Serialize and Deserialize Binary Tree", "Hard", "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "tree"),
            q("20-36", "Binary Tree Maximum Path Sum", "Hard", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "tree"),
            q("20-37", "Vertical Order Traversal of a Binary Tree", "Hard", "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", "tree"),
            q("20-38", "Binary Tree Cameras", "Hard", "https://leetcode.com/problems/binary-tree-cameras/", "tree"),
            q("20-39", "Sum of Distances in Tree", "Hard", "https://leetcode.com/problems/sum-of-distances-in-tree/", "tree"),
            q("20-40", "Number of Ways to Reconstruct a Tree", "Hard", "https://leetcode.com/problems/number-of-ways-to-reconstruct-a-tree/", "tree"),
            q("20-41", "Redundant Connection II", "Hard", "https://leetcode.com/problems/redundant-connection-ii/", "tree"),
        ]
    },
    {
        id: "21",
        title: "Hash Table",
        description: "Use hash maps for O(1) lookups and efficient data organization.",
        slug: "hash-table",
        questions: [
            // EASY
            q("21-1", "Verifying an Alien Dictionary", "Easy", "https://leetcode.com/problems/verifying-an-alien-dictionary/", "hash-table"),
            q("21-2", "Design HashMap", "Easy", "https://leetcode.com/problems/design-hashmap/", "hash-table"),
            // MEDIUM
            q("21-3", "Top K Frequent Elements", "Medium", "https://leetcode.com/problems/top-k-frequent-elements/", "hash-table"),
            q("21-4", "Design Twitter", "Medium", "https://leetcode.com/problems/design-twitter/", "hash-table"),
        ]
    },
    {
        id: "22",
        title: "Binary Search",
        description: "Efficiently search sorted data by repeatedly dividing the search interval in half.",
        slug: "binary-search",
        questions: [
            // EASY
            q("22-1", "Sqrt(x)", "Easy", "https://leetcode.com/problems/sqrtx/", "binary-search"),
            q("22-2", "Binary Search", "Easy", "https://leetcode.com/problems/binary-search/", "binary-search"),
            q("22-3", "Count Negative Numbers in a Sorted Matrix", "Easy", "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/", "binary-search"),
            q("22-4", "Peak Index in a Mountain Array", "Easy", "https://leetcode.com/problems/peak-index-in-a-mountain-array/", "binary-search"),
            // MEDIUM
            q("22-5", "Time Based Key-Value Store", "Medium", "https://leetcode.com/problems/time-based-key-value-store/", "binary-search"),
            q("22-6", "Search in Rotated Sorted Array", "Medium", "https://leetcode.com/problems/search-in-rotated-sorted-array/", "binary-search"),
            q("22-7", "Pow(x, n)", "Medium", "https://leetcode.com/problems/powx-n/", "binary-search"),
            q("22-8", "Find First and Last Position of Element in Sorted Array", "Medium", "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", "binary-search"),
            q("22-9", "Find Peak Element", "Medium", "https://leetcode.com/problems/find-peak-element/", "binary-search"),
            q("22-10", "Search a 2D Matrix", "Medium", "https://leetcode.com/problems/search-a-2d-matrix/", "binary-search"),
            q("22-11", "Divide Two Integers", "Medium", "https://leetcode.com/problems/divide-two-integers/", "binary-search"),
            q("22-12", "Capacity To Ship Packages Within D Days", "Medium", "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", "binary-search"),
            q("22-13", "Minimum Limit of Balls in a Bag", "Medium", "https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/", "binary-search"),
            // HARD
            q("22-14", "Median of Two Sorted Arrays", "Hard", "https://leetcode.com/problems/median-of-two-sorted-arrays/", "binary-search"),
            q("22-15", "Count of Smaller Numbers After Self", "Hard", "https://leetcode.com/problems/count-of-smaller-numbers-after-self/", "binary-search"),
            q("22-16", "Max Sum of Rectangle No Larger Than K", "Hard", "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/", "binary-search"),
            q("22-17", "Split Array Largest Sum", "Hard", "https://leetcode.com/problems/split-array-largest-sum/", "binary-search"),
            q("22-18", "Shortest Subarray with Sum at Least K", "Hard", "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", "binary-search"),
        ]
    },
    {
        id: "23",
        title: "Stack",
        description: "LIFO data structure for parsing, expression evaluation, and monotonic operations.",
        slug: "stack",
        questions: [
            // EASY
            q("23-1", "Min Stack", "Easy", "https://leetcode.com/problems/min-stack/", "stack"),
            q("23-2", "Next Greater Element I", "Easy", "https://leetcode.com/problems/next-greater-element-i/", "stack"),
            q("23-3", "Backspace String Compare", "Easy", "https://leetcode.com/problems/backspace-string-compare/", "stack"),
            q("23-4", "Implement Queue using Stacks", "Easy", "https://leetcode.com/problems/implement-queue-using-stacks/", "stack"),
            q("23-5", "Implement Stack using Queues", "Easy", "https://leetcode.com/problems/implement-stack-using-queues/", "stack"),
            // MEDIUM
            q("23-6", "Remove All Adjacent Duplicates in String II", "Medium", "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/", "stack"),
            q("23-7", "Daily Temperatures", "Medium", "https://leetcode.com/problems/daily-temperatures/", "stack"),
            q("23-8", "Flatten Nested List Iterator", "Medium", "https://leetcode.com/problems/flatten-nested-list-iterator/", "stack"),
            q("23-9", "Online Stock Span", "Medium", "https://leetcode.com/problems/online-stock-span/", "stack"),
            q("23-10", "Minimum Cost Tree From Leaf Values", "Medium", "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/", "stack"),
            q("23-11", "Sum of Subarray Minimums", "Medium", "https://leetcode.com/problems/sum-of-subarray-minimums/", "stack"),
            q("23-12", "Evaluate Reverse Polish Notation", "Medium", "https://leetcode.com/problems/evaluate-reverse-polish-notation/", "stack"),
        ]
    },
    {
        id: "24",
        title: "Design",
        description: "System design problems involving data structures and algorithms.",
        slug: "design",
        questions: [
            q("24-1", "LRU Cache", "Medium", "https://leetcode.com/problems/lru-cache/", "design"),
            q("24-2", "Find Median from Data Stream", "Hard", "https://leetcode.com/problems/find-median-from-data-stream/", "design"),
            q("24-3", "Design Underground System", "Medium", "https://leetcode.com/problems/design-underground-system/", "design"),
            q("24-4", "LFU Cache", "Hard", "https://leetcode.com/problems/lfu-cache/", "design"),
            q("24-5", "Tweet Counts Per Frequency", "Medium", "https://leetcode.com/problems/tweet-counts-per-frequency/", "design"),
            q("24-6", "All O'one Data Structure", "Hard", "https://leetcode.com/problems/all-oone-data-structure/", "design"),
            q("24-7", "Design Browser History", "Medium", "https://leetcode.com/problems/design-browser-history/", "design"),
        ]
    },
    {
        id: "25",
        title: "Graph",
        description: "Graph traversal, shortest paths, and connectivity problems.",
        slug: "graph",
        questions: [
            // EASY
            q("25-1", "Employee Importance", "Easy", "https://leetcode.com/problems/employee-importance/", "graph"),
            q("25-2", "Find the Town Judge", "Easy", "https://leetcode.com/problems/find-the-town-judge/", "graph"),
            // MEDIUM
            q("25-3", "Evaluate Division", "Medium", "https://leetcode.com/problems/evaluate-division/", "graph"),
            q("25-4", "Accounts Merge", "Medium", "https://leetcode.com/problems/accounts-merge/", "graph"),
            q("25-5", "Network Delay Time", "Medium", "https://leetcode.com/problems/network-delay-time/", "graph"),
            q("25-6", "Find Eventual Safe States", "Medium", "https://leetcode.com/problems/find-eventual-safe-states/", "graph"),
            q("25-7", "Keys and Rooms", "Medium", "https://leetcode.com/problems/keys-and-rooms/", "graph"),
            q("25-8", "Possible Bipartition", "Medium", "https://leetcode.com/problems/possible-bipartition/", "graph"),
            q("25-9", "Most Stones Removed with Same Row or Column", "Medium", "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/", "graph"),
            q("25-10", "Regions Cut By Slashes", "Medium", "https://leetcode.com/problems/regions-cut-by-slashes/", "graph"),
            q("25-11", "Satisfiability of Equality Equations", "Medium", "https://leetcode.com/problems/satisfiability-of-equality-equations/", "graph"),
            q("25-12", "As Far from Land as Possible", "Medium", "https://leetcode.com/problems/as-far-from-land-as-possible/", "graph"),
            q("25-13", "Number of Closed Islands", "Medium", "https://leetcode.com/problems/number-of-closed-islands/", "graph"),
            q("25-14", "Number of Operations to Make Network Connected", "Medium", "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", "graph"),
            q("25-15", "Find the City With the Smallest Number of Neighbors at a Threshold Distance", "Medium", "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", "graph"),
            q("25-16", "Time Needed to Inform All Employees", "Medium", "https://leetcode.com/problems/time-needed-to-inform-all-employees/", "graph"),
        ]
    },
    {
        id: "26",
        title: "Linked List",
        description: "Operations on singly and doubly linked lists including reversal, merging, and cycle detection.",
        slug: "linked-list",
        questions: [
            // EASY
            q("26-1", "Delete Node in a Linked List", "Easy", "https://leetcode.com/problems/delete-node-in-a-linked-list/", "linked-list"),
            q("26-2", "Middle of the Linked List", "Easy", "https://leetcode.com/problems/middle-of-the-linked-list/", "linked-list"),
            q("26-3", "Convert Binary Number in a Linked List to Integer", "Easy", "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/", "linked-list"),
            q("26-4", "Design HashSet", "Easy", "https://leetcode.com/problems/design-hashset/", "linked-list"),
            q("26-5", "Design HashMap", "Easy", "https://leetcode.com/problems/design-hashmap/", "linked-list"),
            q("26-6", "Reverse Linked List", "Easy", "https://leetcode.com/problems/reverse-linked-list/", "linked-list"),
            q("26-7", "Merge Two Sorted Lists", "Easy", "https://leetcode.com/problems/merge-two-sorted-lists/", "linked-list"),
            q("26-8", "Remove Duplicates from Sorted List", "Easy", "https://leetcode.com/problems/remove-duplicates-from-sorted-list/", "linked-list"),
            q("26-9", "Intersection of Two Linked Lists", "Easy", "https://leetcode.com/problems/intersection-of-two-linked-lists/", "linked-list"),
            q("26-10", "Linked List Cycle", "Easy", "https://leetcode.com/problems/linked-list-cycle/", "linked-list"),
            q("26-11", "Palindrome Linked List", "Easy", "https://leetcode.com/problems/palindrome-linked-list/", "linked-list"),
            q("26-12", "Remove Linked List Elements", "Easy", "https://leetcode.com/problems/remove-linked-list-elements/", "linked-list"),
            // MEDIUM
            q("26-13", "Add Two Numbers", "Medium", "https://leetcode.com/problems/add-two-numbers/", "linked-list"),
            q("26-14", "Copy List with Random Pointer", "Medium", "https://leetcode.com/problems/copy-list-with-random-pointer/", "linked-list"),
            q("26-15", "Add Two Numbers II", "Medium", "https://leetcode.com/problems/add-two-numbers-ii/", "linked-list"),
            q("26-16", "Reverse Linked List II", "Medium", "https://leetcode.com/problems/reverse-linked-list-ii/", "linked-list"),
            q("26-17", "Reorder List", "Medium", "https://leetcode.com/problems/reorder-list/", "linked-list"),
            q("26-18", "Remove Nth Node From End of List", "Medium", "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "linked-list"),
            q("26-19", "Flatten a Multilevel Doubly Linked List", "Medium", "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/", "linked-list"),
            q("26-20", "Partition List", "Medium", "https://leetcode.com/problems/partition-list/", "linked-list"),
            q("26-21", "Remove Duplicates from Sorted List II", "Medium", "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/", "linked-list"),
            q("26-22", "Odd Even Linked List", "Medium", "https://leetcode.com/problems/odd-even-linked-list/", "linked-list"),
            q("26-23", "Sort List", "Medium", "https://leetcode.com/problems/sort-list/", "linked-list"),
            q("26-24", "Swap Nodes in Pairs", "Medium", "https://leetcode.com/problems/swap-nodes-in-pairs/", "linked-list"),
            q("26-25", "Rotate List", "Medium", "https://leetcode.com/problems/rotate-list/", "linked-list"),
            // HARD
            q("26-26", "Merge k Sorted Lists", "Hard", "https://leetcode.com/problems/merge-k-sorted-lists/", "linked-list"),
            q("26-27", "Reverse Nodes in k-Group", "Hard", "https://leetcode.com/problems/reverse-nodes-in-k-group/", "linked-list"),
        ]
    },
    {
        id: "27",
        title: "Heap",
        description: "Priority queue operations for finding k-th elements and maintaining sorted streams.",
        slug: "heap",
        questions: [
            // MEDIUM
            q("27-1", "K Closest Points to Origin", "Medium", "https://leetcode.com/problems/k-closest-points-to-origin/", "heap"),
            q("27-2", "Kth Largest Element in an Array", "Medium", "https://leetcode.com/problems/kth-largest-element-in-an-array/", "heap"),
            q("27-3", "Reorganize String", "Medium", "https://leetcode.com/problems/reorganize-string/", "heap"),
            q("27-4", "Furthest Building You Can Reach", "Medium", "https://leetcode.com/problems/furthest-building-you-can-reach/", "heap"),
            q("27-5", "Kth Smallest Element in a Sorted Matrix", "Medium", "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", "heap"),
            q("27-6", "Cheapest Flights Within K Stops", "Medium", "https://leetcode.com/problems/cheapest-flights-within-k-stops/", "heap"),
            q("27-7", "Find the Most Competitive Subsequence", "Medium", "https://leetcode.com/problems/find-the-most-competitive-subsequence/", "heap"),
            q("27-8", "Ugly Number II", "Medium", "https://leetcode.com/problems/ugly-number-ii/", "heap"),
            // HARD
            q("27-9", "Merge k Sorted Lists", "Hard", "https://leetcode.com/problems/merge-k-sorted-lists/", "heap"),
            q("27-10", "Sliding Window Maximum", "Hard", "https://leetcode.com/problems/sliding-window-maximum/", "heap"),
            q("27-11", "The Skyline Problem", "Hard", "https://leetcode.com/problems/the-skyline-problem/", "heap"),
            q("27-12", "Trapping Rain Water II", "Hard", "https://leetcode.com/problems/trapping-rain-water-ii/", "heap"),
            q("27-13", "Minimum Number of Refueling Stops", "Hard", "https://leetcode.com/problems/minimum-number-of-refueling-stops/", "heap"),
            q("27-14", "Swim in Rising Water", "Hard", "https://leetcode.com/problems/swim-in-rising-water/", "heap"),
            q("27-15", "Shortest Path to Get All Keys", "Hard", "https://leetcode.com/problems/shortest-path-to-get-all-keys/", "heap"),
            q("27-16", "Minimum Cost to Hire K Workers", "Hard", "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/", "heap"),
            q("27-17", "K-th Smallest Prime Fraction", "Hard", "https://leetcode.com/problems/k-th-smallest-prime-fraction/", "heap"),
        ]
    },
];
